Repository uber-web/thrift2flow, pull requests merged in 2019-03, with the labels that each got.

#63 Adds a collection of updates related to tests and type generation
  .flowconfig
  CHANGELOG.md
  package.json
  src/__tests__/__snapshots__/enums.test.js.snap
  src/__tests__/collections/collections.test.js
  src/__tests__/collections/fixtures/index.js.fixture
  src/__tests__/consts/consts.test.js
  src/__tests__/consts/index.js.fixture
  src/__tests__/enums.test.js
  src/__tests__/fixtures/const-enum-values.thrift
  src/__tests__/fixtures/enum-typedef-struct.thrift
  src/__tests__/fixtures/my-enum-with-typedef.thrift
  src/__tests__/fixtures/union-long-import.thrift
  src/__tests__/imports.test.js
  src/__tests__/primitives.test.js
  src/__tests__/services.test.js
  src/__tests__/typedefs.test.js
  src/__tests__/unions.test.js
  src/__tests__/util.js
  src/main/ast-types.js
  src/main/cli.js
  src/main/convert.js
  src/main/index.js
  src/main/thrift-types.js
Labels: feature

#65 Fix enums int64
  src/__tests__/primitives.test.js
  src/main/ast-types.js
  src/main/convert.js
Labels: bugfix

#66 Add more libdefs
  flow-typed/npm/mkdirp_vx.x.x.js
  flow-typed/npm/yargs_vx.x.x.js
  src/main/cli.js
Labels: bugfix

#68 Release v0.7.0
  package.json
Labels: release

#67 Update changelog and readme
  CHANGELOG.md
  README.md
Labels: docs

#69 Update optional properties to be optional properties with nullable values
  src/__tests__/fixtures/optional-struct.thrift
  src/__tests__/primitives.test.js
  src/__tests__/struct.test.js
  src/__tests__/unions.test.js
  src/main/convert.js
Labels: bugfix

#71 Release v0.7.1
  package.json
Labels: release
