Repository uber-web/thrift2flow, pull requests merged in 2019-05, with the labels that each got.

#80 Run prettier to reformat code
  src/__tests__/collections/collections.test.js
  src/__tests__/consts/const-lists.test.js
  src/__tests__/consts/consts.test.js
  src/__tests__/consts/i64.test.js
  src/__tests__/enums.test.js
  src/__tests__/imports.test.js
  src/__tests__/primitives.test.js
  src/__tests__/services.test.js
  src/__tests__/struct.test.js
  src/__tests__/typedefs.test.js
  src/__tests__/unions.test.js
  src/flow-entry.js
  src/main/ast-types.js
  src/main/cli.js
  src/main/convert.js
  src/main/index.js
  src/main/thriftrw.js
  src/test-util.js
Labels: enhancement, feature

#79 Fix an issue preventing compilation when using built in type literals…
  src/__tests__/consts/consts.test.js
  src/__tests__/enums.test.js
  src/__tests__/identifiers/def.thrift
  src/__tests__/identifiers/false.test.js
  src/main/convert.js
Labels: bugfix

#84 Release v0.7.4
  package.json
Labels: release
