Repository uber-web/thrift2flow, pull requests merged in 2019-02, with the labels that each got.

#48 Split up a cli export and a main export
  package.json
  src/main/cli.js
  src/main/index.js
Labels: feature

#49 Release v0.6.1-0
  package.json
Labels: release

#58 Upgrade Flow to 0.93.0
  package.json
  src/main/convert.js
Labels: bugfix

#59 Switch to babel 7
  .babelrc
  babel.config.js
  package.json
Labels: bugfix

#60 Migrate from Tape to Jest
  .eslintrc
  .gitignore
  .npmignore
  flow-typed/npm/jest_v24.x.x.js
  package.json
  src/__tests__/collections/collections.test.js
  src/__tests__/collections/fixtures/index.js.fixture
  src/__tests__/collections/fixtures/types.thrift.fixture
  src/__tests__/consts/consts.test.js
  src/__tests__/consts/index.js.fixture
  src/__tests__/consts/types.thrift.fixture
  src/__tests__/enums.test.js
  src/__tests__/imports.test.js
  src/__tests__/primitives.test.js
  src/__tests__/services.test.js
  src/__tests__/specs/shared.thrift
  src/__tests__/specs/subdir/tutorial.thrift
  src/__tests__/typedefs.test.js
  src/__tests__/unions.test.js
  src/__tests__/util.js
  src/main/convert.js
  src/test/collections.spec.js
  test-output/.gitkeep
Labels: bugfix

#57 Remove timestamp generated comment
  src/main/convert.js
Labels: bugfix

#61 Add snapshots for enums.
  src/__tests__/__snapshots__/enums.test.js.snap
  src/__tests__/enums.test.js
  src/__tests__/fixtures/my-enum.thrift
Labels: bugfix
